### ISSUE TITLE
Support login_hint for createLoginURL

### ISSUE THREAD

**Issue by kenchan0130** [mactroll/OIDCLite#2]
OIDC login URL can have a `login_hint` param.
ref: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

If you already know the login ID, it improves the UX.

**Comment by mactroll** [comment]
🤔 

Since OIDCLite doesn't actually submit the URL to an ASWebAuthentication session, or other WebView... is there much benefit to OIDCLite adding that parameter instead of having your app do it before you pass the URL on?

**Comment by kenchan0130** [comment]
We need to think about the **responsibilities** of the method before we talk about the benefits.

I think it depends on what you consider the responsibilities of OIDCLite's `createLoginURL` method to be.

If the method is responsible for issuing an OIDC login URL, then I think it should support the content based on the OIDC specification.

If there are no responsibilities, then my request itself should be withdrawn, as there is no obligation to absorb the specification in that method.

**Comment by kenchan0130** [comment]
@mactroll 
I would really appreciate it if you could respond to the question above.
